### ISSUE TITLE
Debug Controllers

### ISSUE THREAD

**Issue by AlejandroBeltre** [AlejandroBeltre/HemoRed#3]
Debug the BloodBagController and BloodBankController on the Controller folder of the backend project.

The problem this controllers are causing are that one of them is causing a redirectiong of the API and causig error of definition. This controllers have been comented out and should be uncommented to debug it.

This Issue is assigned to @EqualNoches.

**Comment by EqualNoches** [comment]
Update on the BloodBag controller issue. We're hitting a roadblock with testing because the Donation controller isn't finished yet. The BloodBank controller depends on it, so we can't move forward without it.

I'm not going to close this issue just yet. Instead, I'll create a new issue to highlight that we need to finish the User and Donation controllers first. Once those are done, we can come back and properly test the BloodBank controller.

**Comment by EqualNoches** [comment]
Description

We have debugged the BloodBagController and BloodBankController located in the Controller folder of the backend project. The issues causing API redirection and definition errors have been identified and resolved. The controllers were previously commented out and have now been uncommented for successful debugging.
